require 'travis/api/app'

class Travis::Api::App
  class Endpoint
    # Artifacts are generated by builds. Currently we only expose logs as
    # artifacts
    class Artifacts < Endpoint
      # Fetches an artifact by it's *id*.
      get '/:id' do |id|
        respond_with service(:find_artifact, params)
      end

      # TODO needs auth, required for live log archiving on log:aggregted in travis-tasks
      #
      # put '/:id' do |id|
      #   respond_with service(:update_artifact, params)
      # end
    end
  end
end
