test:
  admins:
    - travisbot
  api_endpoint:
    'https://api-fake.travis-ci.com'
  billing_endpoint:
    'https://billing-fake.travis-ci.com'
  redis:
    url: redis://localhost:6379
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  service_hook_url: https://notify.fake.travis-ci.com
