test:
  admins:
    - travisbot
  api_endpoint:
    'https://api-fake.travis-ci.com'
  billing_endpoint:
    'https://billing-fake.travis-ci.com'
  redis:
    url: redis://localhost:6379
  encryption:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  providers:
    github:
      base_url: https://github.com/
  v3:
    token: xxxxxxxxxxxx
  vcs:
    endpoint: https://api-fake.travis-ci.com
    token: fake-token
  service_hook_url: https://notify.fake.travis-ci.com
  plans:
    github-one-build:
      builds: 1
      github_id: 1206
      name: Bootstrap
      price: 8900
    travis-ci-one-build:
      builds: 1
      name: Bootstrap
      price: 6900
    travis-ci-one-build-annual:
      annual: true
      builds: 1
      name: Bootstrap
      price: 75900
    travis-ci-two-builds:
      builds: 2
      name: Startup
      price: 12900
    travis-ci-two-builds-annual:
      annual: true
      builds: 2
      name: Startup
      price: 141900
    travis-ci-two-premium-builds:
      builds: 2
      flip: travis-ci-two-premium-builds
      name: Custom (2 Jobs and Premium VMs)
      price: 25800
    travis-ci-two-premium-builds-annual:
      annual: true
      builds: 2
      flip: travis-ci-two-premium-builds-annual
      name: Custom (2 Jobs annual and Premium VMs)
      price: 283800
