#!/usr/bin/env ruby
# encoding: UTF-8

require 'bundler/setup'
require 'travis/api/app'
require 'pry'

class Travis::Console
  include Travis::Services
  attr_reader :current_user

  def set_user(user)
    user = User.find_by_login(user) unless User === user
    @current_user = user
  end
end

Travis::Api::App.setup
console = Travis::Console.new
methods = Travis::Console.instance_methods - Object.instance_methods
console.pry(quiet: true, prompt: Pry::SIMPLE_PROMPT)
