#!/bin/bash

set -ev

quay_image=quay.io/travisci/travis-api;
local_image=travis-api

branch=$(echo $TRAVIS_BRANCH | sed -e 's/\//-/g')
commit=${TRAVIS_COMMIT:0:7}

docker build . -t $local_image

docker login -u="$QUAY_ROBOT_HANDLE" -p="$QUAY_ROBOT_TOKEN" quay.io;

docker images;

docker tag $local_image $quay_image:$branch;
docker push $quay_image:$branch;

docker tag $local_image $quay_image:$commit;
docker push $quay_image:$commit;

if [ ${branch} = "master" ]; then
  docker tag $local_image $quay_image:latest;
  docker push $quay_image:$branch;
fi

exit 0;
