#!/usr/bin/env bash

cd "$(dirname "$0")/.."

for d in $TWEMPROXY_ENABLED_FOR_DYNOS; do
  if [ "$d" = "$DYNO" ]; then
    export TWEMPROXY_ENABLED=true
  fi
done

if [ ! -f "bin/start-twemproxy" ]; then
  echo "warning: twemproxy buildpack not found, setting TWEMPROXY_ENABLED=false"
  export TWEMPROXY_ENABLED=false
fi

if [ "$TWEMPROXY_ENABLED" = '1' ] || [ "$TWEMPROXY_ENABLED" = 'true' ]; then
  exec bin/start-twemproxy script/server-pgbouncer
else
  exec script/server-pgbouncer
fi
