#!/usr/bin/env bash
cd "$(dirname "$0")/.."
[ $PORT ]     || PORT=3000
[ $RACK_ENV ] || RACK_ENV=development

cmd="ruby -I lib -S bundle exec ruby -I lib -S unicorn config.ru -E $RACK_ENV -c config/unicorn.rb"
[[ $RACK_ENV == "development" ]] && exec rerun "$cmd -l 127.0.0.1:$PORT"
exec $cmd
